name: Basic Tests

on: [push]

env:
  NODE_VERSION: 18

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node packages
        run: npm ci

      - name: Run static code check
        run: npm run lint
      - name: Run test script
        run: ./test.sh
